_ffi_include_dir="$(pkg-config --cflags-only-I libffi | sed 's|^-I||g')"

cmake -G "Unix Makefiles" -Wno-dev \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_VERBOSE_MAKEFILE=NO \
		\
		-DFFI_INCLUDE_DIR="$_ffi_include_dir" \
		-DLLVM_BINUTILS_INCDIR=/usr/include \
		-DLLVM_BUILD_DOCS=YES \
		-DLLVM_BUILD_EXAMPLES=NO \
		-DLLVM_BUILD_EXTERNAL_COMPILER_RT:BOOL=ON \
		-DLLVM_BUILD_LLVM_DYLIB:BOOL=ON \
		-DLLVM_BUILD_TESTS=YES \
		-DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-alpine-linux-musl \
		-DLLVM_DYLIB_EXPORT_ALL:BOOL=ON \
		-DLLVM_ENABLE_ASSERTIONS=NO \
		-DLLVM_ENABLE_CXX1Y=YES \
		-DLLVM_ENABLE_FFI=YES \
		-DLLVM_ENABLE_LIBCXX=YES \
		-DLIBCXX_ENABLE_SHARED:BOOL=OFF \
		-DLIBCXXABI_ENABLE_SHARED:BOOL=OFF \
		-DLLVM_ENABLE_PIC=YES \
		-DLLVM_ENABLE_RTTI=YES \
		-DLLVM_ENABLE_SPHINX=YES \
		-DLLVM_ENABLE_TERMINFO=YES \
		-DLLVM_ENABLE_ZLIB=YES \
		-DLLVM_HOST_TRIPLE=x86_64-alpine-linux-musl \
		-DLLVM_INCLUDE_EXAMPLES=NO \
		-DLLVM_LINK_LLVM_DYLIB:BOOL=ON \
		-DLLVM_TARGETS_TO_BUILD=all \
		\
		-DSPHINX_WARNINGS_AS_ERRORS=NO ../llvm
